### ISSUE TITLE
sqlserer image doesn't work in M1 macbook

### ISSUE THREAD

**Issue by yumikohey** [PacktPublishing/Building-Modern-SaaS-Applications-with-C-and-.NET#1]
when I run `docker compose up`, I got this 
Attaching to dev-env, sqlserver
sqlserver  | SQL Server 2022 will run as non-root by default.
sqlserver  | This container is running as user mssql.
sqlserver  | To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
sqlserver  | /opt/mssql/bin/sqlservr: Invalid mapping of address 0x4003bac000 in reserved address space below 0x400000000000. Possible causes:
sqlserver  | 1) the process (itself, or via a wrapper) starts-up its own running environment sets the stack size limit to unlimited via syscall setrlimit(2);
sqlserver  | 2) the process (itself, or via a wrapper) adjusts its own execution domain and flag the system its legacy personality via syscall personality(2);
sqlserver  | 3) sysadmin deliberately sets the system to run on legacy VA layout mode by adjusting a sysctl knob vm.legacy_va_layout.
sqlserver  | 
sqlserver exited with code 1

**Comment by yumikohey** [comment]
This can be fixed if you update `docker-compose.yml` file like this.
```
version: '3.9'
services:
  sql_server:
    container_name: sqlserver
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    ports:
      - "9876:1433"
    volumes:
      - habit-db-volume:/var/opt/mssql
    env_file:
      - sqlserver/sqlserver.env
  dev-env:
    container_name: dev-env
    build:
      context: ./dev-env
    volumes:
      - "..:/workspace"
    stdin_open: true # docker run -i
    tty: true # docker run -t
volumes:
  habit-db-volume: null
```

**Comment by yumikohey** [comment]
By using azure-edge-sql, sqlcmd tool is not available inside the ARM64 version of SQL Edge containers though. It's being declared on Docker hub description, https://hub.docker.com/_/microsoft-azure-sql-edge?tab=description

To access SQL Server command-line interface, you will need to create additional docker container, follow this
https://stackoverflow.com/a/72529145/4168649

**Comment by yumikohey** [comment]
To successfully access SQL Server command-line interface, you will need to configure in this way,
https://forums.docker.com/t/sqlcmd-cannot-connect-to-sql-instance-container-to-container/89401/5

Here is my e2e docker-compose.yml working version
```
version: '3.9'
services:
  sql_server:
    container_name: sqlserver
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    ports:
      - "9876:1433"
    volumes:
      - habit-db-volume:/var/opt/mssql
    env_file:
      - sqlserver/sqlserver.env
    networks:
      - db_net
  dev-env:
    container_name: dev-env
    build:
      context: ./dev-env
    volumes:
      - "..:/workspace"
    stdin_open: true # docker run -i
    tty: true # docker run -t
    networks:
      - db_net
  sqlcmd:
    image: mcr.microsoft.com/mssql-tools:latest
    stdin_open: true
    env_file:
      - sqlserver/sqlserver.env
    volumes:
      - ./mssql_scripts:/opt/mssql_scripts
    networks:
      - db_net
volumes:
  habit-db-volume: null
networks:
  db_net:
    name: db_net
```

Open a new terminal, run `/opt/mssql-tools/bin/sqlcmd`
Then,  run `sqlcmd -S sqlserver -U SA` and prompt for password
